name: OWASP ZAP Itegration
on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
        env:
          ACTIONS_STEP_DEBUG: true
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://solosavings.wanl.blue/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'