name: Security Scan

on:
  push:
    branches:
      - main

jobs:
  
  software_anaylsis_sca:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Install Snyk CLI
        run: npm install -g snyk
        working-directory: ./code/SoloSavingsApp
  
      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
        working-directory: ./code/SoloSavingsApp
  
      - name: Change to App Directory
        run: cd ./code/SoloSavingsApp
  
      - name: Run Snyk Test
        run: snyk test --all-sub-projects -- -Dmaven=mvnw
        working-directory: ./code/SoloSavingsApp

  
  