name: Security Scan (Automated Testing)

on:
  push:
    branches:
      - main

jobs:
  security_scan_sast:
    runs-on: ubuntu-latest
    name: Static Application Security Testing (SAST)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Install Maven
        run: sudo apt-get install -y maven  # Install Maven if not pre-installed

      - name: Build with Maven
        run: mvn clean install -DskipTests
        working-directory: ./code/SoloSavingsApp

      - name: Analyze with SonarCloud
        run: mvn -f ./code/SoloSavingsApp/pom.xml -B verify sonar:sonar -Dsonar.projectKey=javaprojectreachabilitysq -Dsonar.organization=javaprojectreachabilitysq -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  

  security_scan_dast:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Build with Maven
      run: mvn clean install -DskipTests
      working-directory: ./code/SoloSavingsApp

    - name: Start Tomcat container
      run: docker run -d -p 8080:8080 --name tomcat tomcat:8.5
      working-directory: ./code/SoloSavingsApp

    - name: Copy WAR file to container
      run: docker cp target/*.war tomcat:/usr/local/tomcat/webapps
      working-directory: ./code/SoloSavingsApp

    - name: Wait for app to start
      run: |
        while ! curl -s http://localhost:8080; do
          sleep 1
        done

    - name: Run OWASP ZAP DAST
      uses: zaproxy/action-baseline@v0.10.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
        target: 'http://localhost:8890/solosavings'
        rules_file_name: '.zap/rules.tsv'
        cmd_options: '-a'
        