name: Security Scan

on:
  push:
    branches:
      - main

jobs:
  sast:
    runs-on: ubuntu-latest
    name: Static Application Security Testing (SAST)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Install Maven
        run: sudo apt-get install -y maven  # Install Maven if not pre-installed

      - name: Build with Maven
        run: mvn clean install -DskipTests
        working-directory: ./code/SoloSavingsApp

      - name: Analyze with SonarCloud
        run: mvn -f ./code/SoloSavingsApp/pom.xml -B verify sonar:sonar -Dsonar.projectKey=javaprojectreachabilitysq -Dsonar.organization=javaprojectreachabilitysq -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
