name: Security Scan

on:
  push:
    branches:
      - main

jobs:
  sast:
    runs-on: ubuntu-latest
    name: Static Application Security Testing (SAST)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build with Maven
        run: mvn clean install -DskipTests
        working-directory: ./code/SoloSavingsApp

      - name: Analyze with SonarCloud
        run: mvn -B verify sonar:sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          

  software_anaylsis_sca:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Install Snyk CLI
        run: npm install -g snyk
        working-directory: ./code/SoloSavingsApp
  
      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
        working-directory: ./code/SoloSavingsApp
  
      - name: Run Snyk Test
        run: snyk test --all-sub-projects -- -Dmaven=mvnw
        working-directory: ./code/SoloSavingsApp

  
  